### ISSUE TITLE
logistf plt

### ISSUE THREAD

**Issue by Kagereki** [strengejacke/sjPlot#11]
Is there a function to plot the logistf?

**Comment by sjPlot** [comment]
I need to install the package and see the structure of the logistf-object. Maybe it already works with sjPlot.

**Comment by Kagereki** [comment]
Thanks. Will be waiting for feedback on your experience.

**Comment by sjPlot** [comment]
Ok, `logistf`support added to `sjp.glm`, with some limitations (as described [here](http://stackoverflow.com/a/29014963/2094622)).

Does this work for you?

**Comment by mdhquan** [comment]
I specified a model using the logistf function and saved the results as an object titled "model2". I then tried sjp.glm(model2) and received the following error:

Error in UseMethod("family") : 
  no applicable method for 'family' applied to an object of class "logistf"

This is really strange, since I think sjp.glm supports logistf objects, and I have the newest versions of sjmisc and sjPlot. Please advise?

**Comment by strengejacke** [comment]
I have revised the functions, to be more generic. I'll look into this issue... But this is in first place an issue of the maintainer of the logistf-function/pkg, because that package should provide a family-method.

**Comment by mdhquan** [comment]
Very strange indeed. Thank you for your update. Please let me know when I can try the block of codes that I sent you again.

Best,

- Quan
