### ISSUE TITLE
sjPlot for generalized additive models/mixed models of gam/gamm4 class

### ISSUE THREAD

**Issue by mainambui** [strengejacke/sjPlot#131]
I'd like to visualize $gam and $mer components of additive models. Can this be implementd easily?

**Comment by sjPlot** [comment]
I have not worked with these kinds of models yet, so I need some practice to understand the object structure for these models in order to support them in **sjPlot**. As long as these packages also provide generic functions like `predict`, `summary`, `model.frame` etc., implementation should be fairly easy.

**Comment by sjPlot** [comment]
Another example, sent to me by email:

```
#http://www.ats.ucla.edu/stat/r/dae/poissonreg.htm

p <- read.csv("http://www.ats.ucla.edu/stat/data/poisson_sim.csv")
p <- within(p, {
  prog <- factor(prog, levels=1:3, labels=c("General", "Academic", "Vocational"))
  id <- factor(id)
})

mod.glm <- glm(data = p, 
             num_awards ~ 
             prog + math,
             family=poisson(link= log))
summary(mod.glm)

mod.gam.same.as.glm <- mgcv::gam(data = p, 
             num_awards ~ 
             prog + math,
             family=poisson(link= log))
summary(mod.gam.same.as.glm)

mod.gam.spline <- mgcv::gam(data = p, 
             num_awards ~ 
             prog + s(math),
             family=poisson(link= log))
summary(mod.gam.spline)
plot(mod.gam.spline)

```

**Comment by strengejacke** [comment]
The problem is that there are at least three packages, which define the `gam`-class: **gam**, **mgcv** and **gamm4**. All of those handle the `gam`-component in a different way, so the structure of these objects is not identical.

There is no way to decide which gam-object I have, so I decided to go for `mgcv::gam`. For `gamm4`, you can plot the `$mer`-component.

I think this is an issue, where the maintainers of the above packages should find a way to harmonize their objects or add a unique class identifier.
