### ISSUE TITLE
Points change completely after changing their colors in sjp.lmer

### ISSUE THREAD

**Issue by DemaLM** [strengejacke/sjPlot#266]
Hi, 

when I use the sj.lmer to plot the predicted effects of the model and change the colors of the points (point.color) or point.alpha, the points have their position changed as well.

The model
`modlmer<- lmer ( WCM ~ scat.h + sVfr +(1| Species), temp[-c(3,13)] )`

`sjp.lmer(modlmer, type = "pred", vars="scat.h",  point.alpha =  0.2, show.scatter = TRUE)`

![image](https://user-images.githubusercontent.com/19428346/29488170-5692deb8-84fd-11e7-8b89-2792efcb0b77.png)

`sjp.lmer(modlmer, type = "pred", vars="scat.h",  point.alpha =  0.5, show.scatter = TRUE)`

![image](https://user-images.githubusercontent.com/19428346/29488175-6e2cc00c-84fd-11e7-9642-3b5637eae0b5.png)

What might be the problem here?

Cheers

**Comment by strengejacke** [comment]
This is because the data points are plotted using `geom_jitter()`, thus a small random variation is added to the dot positions. See `?sjp.lmer` => `show.scatter`. That's why the position of dots changes each time you call the function.

I have addressed this issue in the forthcoming [geffects](https://github.com/strengejacke/ggeffects)-update. **ggeffects** will internally be used by **sjPlot** in the future, to plot predicted values.

You can either wait for the next major sjPlot-update (somewhen in September), or for the next ggeffects-updare (somewhen next week), and do following:

```
library(ggeffects)
dat <- ggpredict(modlmer, terms = "scat.h")
plot(
  dat,
  rawdata = TRUE # add scatter plot with data points,
  jitter = FALSE # no random variation of dot positions,
  dot.alpha = .2 # alpha of data points
)
```

**Comment by DemaLM** [comment]
Thanks. 

But for me it's not clear why: although the dots don't represent the exact data values, why are they jittered differentially for color changes?

**Comment by strengejacke** [comment]
It's not the color change, it's just that the random variation is different each time you re-create (i.e. call the function again) the plot. The dot positions will always change for each function call, even if you don't change the arguments.

**Comment by DemaLM** [comment]
Ok, 
cheers
