### ISSUE TITLE
can't update sjPlot from github - wrong ggeffects version

### ISSUE THREAD

**Issue by b1azk0** [strengejacke/sjPlot#322]
sjPlot depends on ggeffects 0.3.1 where the last version in github is 0.3.0.9

After running this sequence:
```

devtools::install_github("strengejacke/sjlabelled", force=TRUE)
devtools::install_github("strengejacke/sjmisc")
devtools::install_github("strengejacke/sjstats", force=TRUE)
devtools::install_github("strengejacke/ggeffects", force = TRUE)
devtools::install_github("strengejacke/sjPlot", force = TRUE)
```

I get an error when running last line

```
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace 'ggeffects' 0.3.0.9000 is being loaded, but >= 0.3.1 is required
ERROR: lazy loading failed for package 'sjPlot'
```

**Comment by strengejacke** [comment]
Yes, that's the preparation for the next release cycle of my packages. _sjstats_ is just updated on CRAN, _ggeffects_ will be submitted in 1-2 days, then _sjPlot_ submission will follow. Pls wait 1-2 days, then you can install from GitHub again, or just wait for the update on CRAN (to come soon, in about 1 week).

**Comment by b1azk0** [comment]
Thank for the quick answer.
I was compiling my next phd and got a panic attack when all the sudden my whole markdown stopped rendering properly.

Is the github version going to work properly sooner than CRAN? (this applies also to sjt.grpmean() issue I reported as I used that pretty heavily).

**Comment by strengejacke** [comment]
You can download the latest versions as source pkg here:
[ggeffects_0.3.1.tar.gz](https://github.com/strengejacke/sjPlot/files/1629828/ggeffects_0.3.1.tar.gz)

[sjPlot_2.4.0.9000.tar.gz](https://github.com/strengejacke/sjPlot/files/1629832/sjPlot_2.4.0.9000.tar.gz)

You just need to remove _ggeffects_ and update from CRAN again the next days, once version 0.3.1 is available. Just checking for updates won't recognize any new submission, since the pkg version in the above download is the same as from the forthcoming update.

**Comment by b1azk0** [comment]
Thanks a lot!!
