### ISSUE TITLE
question about plotting interaction with linear term from glmer

### ISSUE THREAD

**Issue by dfareri** [strengejacke/sjPlot#458]
Hi, 

I am somewhat new to this package, and am trying to use it to plot an interaction from a mixed effects logistic regression (glmer) using plot_model.  I am able to successfully generate a plot, but I have a question about its interpretation and display which I am hoping someone might be able to assist with.

First, the outcome here is dichotomous (1/0, representing a correct or incorrect choice, respectively), and the generated plot shows percentages on the y-axis. I am interpreting to be the predicted probability of a participant choosing correctly (1) over incorrectly (0) on a given trial.  Would that interpretation of the plot be correct?  Basically, I am looking at performance (correct/incorrect on a probabilistic learning task) as a function of age and learning context. 

Second, my independent variable on the x-axis here is age (modeled linearly), but one of the plot lines on the graph representing learning context appears to have a slight curve to it which seems somewhat strange to me.  Would that have something to do with the method in which plot_model is estimating the predicted probabilities as a function of the predictor here?

Any suggestions would be appreciated. 

-Dominic

**Comment by strengejacke** [comment]
Hi Dominic,
your interpretation of the predicted probability is correct. The lines do not have to be straight lines, especially since you have log-transformed y-scales for non-Gaussian models. sjPlot resp. `plot_model()` simply wraps the functions from the *ggpredict* package. There, you find a vignette comparing Stata's with ggpredict's output, the example involves a logistic regression with interaction terms (both continuous, modelled linear). There you can see that one line is also curved, while the other one ist straight: https://strengejacke.github.io/ggeffects/articles/stata.html

**Comment by dfareri** [comment]
Hi Daniel,

Thank you so much for the super quick reply and clarification. I really appreciate it.  And thanks for putting together this awesome package!

Best,
Dominic

**Comment by strengejacke** [comment]
you're welcome! You might be interested in the package vignettes from ggeffects:
https://strengejacke.github.io/ggeffects/
