### ISSUE TITLE
How not to plot reference category in predicted probabilities between categorical variables?

### ISSUE THREAD

**Issue by davidcanarte** [strengejacke/sjPlot#529]
Hello

I am plotting predicted probabilities using this code

p12 <- plot_model(m5_financial, type = "pred", 
                  terms = c("Alter.Age.Brackets", "Tie.Is.Family"), 
                  #colors ="bw", 
                  title = "")

Where "Tie.Is.Family" is a binary "Yes" and "No"
& "Alter.Age.Brackets" has the categories 18-30, 31-40 (reference), 41-60, and >60. 

How could I plot the above without Alter.Age.Bracket's reference category (31-40)? So far is always showing up 

Thanks

**Comment by strengejacke** [comment]
In general, there's nothing wrong with plotting the reference category, since the predicted probabilities are not _with reference_ to any category of the predictors, hence you indeed get predictions for the reference category as well.

But you can plot specific values only. Since `plot_model()` simply uses the **ggeffects** package for effect-plots, you can look [at this help-page](https://strengejacke.github.io/ggeffects/articles/introduction_effectsatvalues.html) for more details.

**Edit** I just saw that `plot_model()` does not allow specific levels when these are not numeric, so you should use **ggeffects** directly:

``` r
library(ggplot2)
library(ggeffects)

data(iris)
set.seed(123)
iris$binary <- rbinom(nrow(iris), size = 1, prob = .3)
m <- lm(Sepal.Width ~ Species * binary, data = iris)

ggpredict(m, terms = c("Species", "binary")) %>% plot()
```

![](https://i.imgur.com/ro2MiOx.png)

``` r

ggpredict(m, terms = c("Species [versicolor,virginica]", "binary")) %>% 
  plot() +
  scale_x_continuous(breaks = c(1, 2), labels = c("versicolor", "virginica"))
#> Scale for 'x' is already present. Adding another scale for 'x', which
#> will replace the existing scale.
```

![](https://i.imgur.com/IJ6llAv.png)

<sup>Created on 2019-08-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by davidcanarte** [comment]
Thanks a lot! Maybe I've not said before, but this package is awesome. Thanks!

**Comment by strengejacke** [comment]
I found out why `plot_model()` fails, a workaround for the momen would be:

``` r
library(sjPlot)
#> #refugeeswelcome

data(iris)
set.seed(123)
iris$binary <- rbinom(nrow(iris), size = 1, prob = .3)
m <- lm(Sepal.Width ~ Species * binary, data = iris)

plot_model(m, terms = c("Species", "binary"), type = "pred")
```

![](https://i.imgur.com/lQPZ0uk.png)

``` r

plot_model(m, terms = c("Species [versicolor,virginica]", "binary"), type = "pred", case = NULL)
```

![](https://i.imgur.com/nIcPFBm.png)

<sup>Created on 2019-08-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by davidcanarte** [comment]
Many thanks! I will work on this asap.

**Comment by strengejacke** [comment]
Just one follow up: labelling the x-axis will also work automatically when you use `x.cat = TRUE`:

```r
ggpredict(m, terms = c("Species [versicolor,virginica]", "binary"), x.cat = TRUE) %>% plot()
```

See also the [get started-vignette](https://strengejacke.github.io/ggeffects/articles/ggeffects.html#printing-factor-levels-instead-of-numeric-values).
