### ISSUE TITLE
sjPlot with lmer model, error

### ISSUE THREAD

**Issue by mroumet** [strengejacke/sjPlot#607]
Hello,

I'm tried to produce a html table using the table function of the sjPlot package and I get a strange error message.  Any idea?

Thanks a lot in advance,
Marie

example: 
library(lmerTest)
fm3 <- lmer(Reaction ~ Days + (Days|Subject), sleepstudy,       REML=TRUE)
sjPlot::tab_model(fm3)
Error in gsub("Statistic", gsub("-statistic", "", attr(statistic, "statistic",  :
  invalid 'replacement' argument

**Comment by strengejacke** [comment]
I think your issue is related to this issue: https://github.com/strengejacke/sjPlot/issues/603

And I guess you can solve it following this instruction:
https://github.com/strengejacke/sjPlot/issues/603#issuecomment-589987190

(or by using lme4 instead of lmerTest)

If not, please re-open this issue.

**Comment by mroumet** [comment]
Thanks
