### ISSUE TITLE
questions about sjPlot

### ISSUE THREAD

**Issue by aexaa21** [strengejacke/sjPlot#614]
Hello guys, 
many thanks for your contributions, 
I have a question about the the function _tab_model_

On this code: 
`tab_model(m1, show.est = TRUE, show.ci = FALSE, show.se = TRUE, show.re.var = TRUE, show.stat = TRUE)`

1.) I am trying to print out the _t_ value, however I am not sure if _show.stat_ would be the same as the _t_ or _z_ values for logistic models. So could you please advise how to find these values, please?

2.) If my model is a mixed effect logistic one, is there anyway I could have have original estimate values (not the odds ratio), and disable them being automatically converted (exponentiated).?

3.) Is there anyway, I can have both the random effects variance and standard deviation in the same table?

Thanks in advance for your help.

**Comment by strengejacke** [comment]
1) This is the test statistic, _z_ for logistic regression models. Note that _sjPlot_ simply uses [`parameters::model_parameters()`](https://easystats.github.io/parameters/reference/model_parameters.html) to get the information used in `tab_model()` or `plot_model()`.

2) Use `transform = NULL` to avoid automatic transformation.

3) SD is returned by `parameters::random_parameters()`, but since it's simply the `sqrt()` of the variance, I decided to not include this information (it gives not much information beyond the RE-variances)

``` r
library(lme4)
library(parameters)
library(sjPlot)
#> #refugeeswelcome

m1 <- glmer(cbind(incidence, size - incidence) ~ period + (1 | herd), data = cbpp, family = binomial)

model_parameters(m1)
#> Parameter   | Coefficient |   SE |         95% CI |     z | df |      p
#> -----------------------------------------------------------------------
#> (Intercept) |       -1.40 | 0.23 | [-1.85, -0.95] | -6.05 | 51 | < .001
#> period [2]  |       -0.99 | 0.30 | [-1.59, -0.40] | -3.27 | 51 | 0.001 
#> period [3]  |       -1.13 | 0.32 | [-1.76, -0.50] | -3.49 | 51 | < .001
#> period [4]  |       -1.58 | 0.42 | [-2.41, -0.75] | -3.74 | 51 | < .001

random_parameters(m1)
#> # Random Effects
#> 
#> Within-Group Variance      3.29 (1.81)
#> Between-Group Variance
#>   Random Intercept (herd)  0.41 (0.64)
#> N (groups per factor)
#>   herd                       15
#> Observations                 56

tab_model(m1, transform = NULL, show.stat = TRUE)
```

<table style="border-collapse:collapse; border:none;"><tr><th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; "></th>
<th colspan="4" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">cbind(incidence,size-incidence)</th></tr>
<tr><td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">Predictors</td><td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">Log-Odds</td><td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">CI</td><td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">Statistic</td><td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">p</td></tr>
<tr><td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">(Intercept)</td><td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-1.40</td><td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-1.85 – -0.95</td><td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-6.05</td><td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.001</td></tr>
<tr><td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">period [2]</td><td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-0.99</td><td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-1.59 – -0.40</td><td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-3.27</td><td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.001</td></tr>
<tr><td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">period [3]</td><td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-1.13</td><td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-1.76 – -0.50</td><td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-3.49</td><td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "><0.001</td></tr><tr><td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">period [4]</td><td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-1.58</td><td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-2.41 – -0.75</td><td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-3.74</td><td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.001</td></tr>
<tr><td colspan="5" style="font-weight:bold; text-align:left; padding-top:.8em;">Random Effects</td></tr>
<tr><td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">s<sup>2</sup></td><td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="4">3.29</td>
<tr><td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">t<sub>00</sub> <sub>herd</sub></td><td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="4">0.41</td><tr><td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">ICC</td><td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="4">0.11</td>
<tr><td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">N <sub>herd</sub></td><td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="4">15</td>
<tr><td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">Observations</td><td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="4">56</td></tr><tr><td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">Marginal R<sup>2</sup> / Conditional R<sup>2</sup></td><td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="4">0.085 / 0.187</td></tr></table>

<sup>Created on 2020-03-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by aexaa21** [comment]
Many thanks @Daniel for your help in answering my questions. Also can not thank you enough   for such an efficient and time saving function _tab model_  from the powerful @sjPlot.
