### ISSUE TITLE
Question: Changing Facet Label in plot_model 

### ISSUE THREAD

**Issue by aja2182** [strengejacke/sjPlot#787]
Thanks for this package, it's made my life so much easier!! I've plotted a three-way interaction. I am having issues with changing the name of one of the faceted variables. I'd like to do this directly inside sjplot (as opposed to changing the variable's name in the dataset). Do I use labeller or is there another approach? I remember reading about it somewhere in the manual but can't seem to find it. Any advice for customizing this plot is appreciated :) 

This is my code: 
plot_m6 <- plot_model(m6, type="pred",
                      colors="system", terms=c("prob_rate01", "cj_referral", "incarceration_rate01[.25, .50, .75, 1]"))

**Comment by ingmnz** [comment]
Hi AJ,

I just stumbled across the same problem and found a solution, albeit it's pretty bulky. I’m certain there are easier ways but this might help out for now. 

First, I assume you are referring to your faceted variable “incarceration_rate01[.25, .50, .75, 1]", which will probably be depicted as “incarceration_rate01 = .25”, “incarceration_rate01 = .50”… and so on in the facet grid? In order to change those labels directly, the following procedure worked for me:

plot_m6 <- plot_model(m6, type="pred", colors="system", terms=c("prob_rate01", "cj_referral", "incarceration_rate01[.25, .50, .75, 1]"))

#rename the chosen facet levels according to your needs; I just used the values you provided
plot_m6$data$facet <- ifelse(plot_m6$data$facet == "incarceration_rate01 = .25", "0.25",
                             ifelse(plot_m6$data$facet == "incarceration_rate01 = .50", "0.50",
                                    ifelse(plot_m6$data$facet == "incarceration_rate01 = .75", "0.75",
                                           ifelse(plot_m6$data$facet == "incarceration_rate01 = 1", "1.0", 99))))

#in case you want to order them in a specific way (R is doing alphabetical orders), you can do the following (taken from #here:https://stackoverflow.com/questions/57080850/adjusting-facet-order-and-legend-labels-when-using-plot-model-#function-of-sjplot):
plot_m6$data$facet <- factor(plot_m6$data$facet, levels = c("0.25", "0.50", "0.75", "1.0"))

plot_m6


I hope, I understood your problem correctly and hope the answer will help out! :)

**Comment by aja2182** [comment]
Thank you @ingmnz!!
