### ISSUE TITLE
Deprecation warning for 'robust' argument

### ISSUE THREAD

**Issue by fquerdasi** [strengejacke/sjPlot#840]
When I run a model for which I would like robust (HC3 type) standard errors: 

`tab_model(model, vcov.fun = "vcovHC", vcov.type = "HC3", show.se=TRUE, show.std=TRUE, show.stat=TRUE, file= "file.html")`

I receive the following warning, and no output is shown: 
`Warning: The `robust` argument is deprecated. Please use `vcov` instead.`

From what I can gather, this happened because the standard_error_robust() and p_value_robust() functions in the parameters() package were superseded by the vcov and vcov_args arguments of the standard_error() and p_value() functions. Is it possible that the tab_model() code needs to be updated to call upon those functions instead of the old ones?

Thanks!

**Comment by fquerdasi** [comment]
I see that this issue is known about and some fixes are documented [here](https://github.com/strengejacke/sjPlot/commit/f29ceac49465560201a4dbbb33ee9aedcd4513f4#diff-8cd20aef2ec96f9eaf279c57708f026f5e507c06545b00a3c6ed69dde1f618ea). As per the example in the updated vignette, when I run the model as: `tab_model(model, vcov.fun = "HC3")`, then it runs fine. However, if I add additional arguments such as: `tab_model(model, vcov.fun = "HC3", show.se=TRUE)` that is when the warning shows up and the output is not given. Hopefully that helps to clarify the issue.

**Comment by TillMK** [comment]
Having a similar issue. When using tab_model with sandwich estimator, the routine does not work anymore, seemingly as it uses deprecated commands. 

tablelmm <- sjPlot::tab_model(
  sel_mod,
  show.ci = 0.95, 
  show.se = TRUE, 
  auto.label = FALSE, 
  show.icc = TRUE,
  show.df = TRUE,
  dv.labels = c("Model"),
  string.se = "SE",
  df.method = "satterthwaite",
  vcov.fun = "vcovCR",
  vcov.type = "CR2"
)
tablelmm

The `robust` argument is deprecated. Please use `vcov` instead.Error: Unable to extract a variance-covariance matrix for model object of class `lmerModLmerTest`. Different
  values of the `vcov` argument trigger calls to the `sandwich` or `clubSandwich` packages in order to
  extract the matrix (see `?insight::get_varcov`). Your model or the requested estimation type may not be
  supported by one or both of those packages.

Could you please update the arguments as soon as possible. Urgently in need of tab_model to run. It works fine without sandwich estimator. Tried to downgrade to older versions of clubsandwich and sandwich with no success. You seem to have control over these commands, hence, it would be great if you could replace them.

Thank you very much
All the best

**Comment by ibrila** [comment]
Having the same problems as @fquerdasi and @TillMK . I would like to be able to use `tab_model` and `plot_model` including heteroskedasticity-consistent standard errors.

**Comment by strengejacke** [comment]
Do you have a reproducible example? And could you also try to install the latest _sjPlot_ package from GitHub, and see if this warning still appears? It should have been resolved.

```r
library(devtools)
devtools::install_github("strengejacke/sjPlot")
```
